# Generated by Django 5.1.2 on 2024-12-01 22:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('sales_date', models.DateField(default=django.utils.timezone.now)),
                ('store_location', models.CharField(max_length=255)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_of_transactions', models.IntegerField()),
                ('inventory_usage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waste_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quarter', models.IntegerField()),
                ('store_location', models.CharField(max_length=255)),
                ('total_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('average_sales', models.DecimalField(decimal_places=2, max_digits=12)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('number_of_transactions', models.IntegerField()),
                ('inventory_usage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_delivery_date', models.DateField()),
                ('total_quantity_ordered', models.IntegerField()),
                ('projected_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
                ('total_cases_ordered', models.IntegerField()),
                ('horizon_projected_sales', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_contact_number', models.CharField(max_length=50)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('vendor_address', models.TextField()),
                ('vendor_lead_time_days', models.IntegerField()),
                ('vendor_minimum_order_quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_on_hand', models.IntegerField()),
                ('reorder_point', models.IntegerField(default=0)),
                ('perishability', models.BooleanField(default=False)),
                ('suggested_quantity_to_order', models.IntegerField(default=0)),
                ('actual_quantity_to_order', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.category')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=50)),
                ('quantity_ordered', models.IntegerField()),
                ('quantity_received', models.IntegerField()),
                ('expected_delivery_date', models.DateField()),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], max_length=50)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='inventory.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('suggested_quantity_to_order', models.IntegerField(default=0)),
                ('actual_quantity_to_order', models.IntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.order')),
                ('order_item_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='inventory.item')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='inventory.vendor'),
        ),
    ]
